# Address to the MariaDB database
# for local runs, change to "localhost"
database_address = "localhost"

# User to access datbaase
database_user = "root"

# Password for the database user
database_password = "shiva7"

# port
database_port = 3306

database_name = "cms-and-go"

# port to run the webserver on
webserver_port = 8080

# Directory to use for string uploaded images.
image_dir = "./images"

[[card_schema]]
schema_name = "schema1"

[[card_schema]]
schema_name = "schema2"