version: '3.8'

services:
  cms_and_go_app:
    image: andrenormanlang/cms-golang:0.2
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ..
        target: /cmsgo
        volume:
          nocopy: true
    command:  /cmsgo/docker/start-app.sh
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net
  
  cms_and_go_admin_app:
    image: andrenormanlang/cms-golang:0.2
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ..
        target: /gocms
        volume:
          nocopy: true
    command:  /cmsgo/start-admin-app.sh
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - common-net
  


  mariadb:
    image: mariadb:11.2.3-jammy
    container_name: mariadb
    env_file:
       - ../.dev.env
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-proot", "-e", "USE cms-and-go" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - common-net

networks:
  common-net: {}