name: Build

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ⚒️

    runs-on: ubuntu-latest
    container:
      image: andrenormanlang/cms-golang:0.1
      options: --user 1001

    steps:
    - uses: actions/checkout@v3
      name: Checking Out Repo 👀
    - name: Golang Build 🐹
      run: make build
    - name: Package 📦
      run: |
        mkdir urchin-ubuntu-build
        cp tmp/cmsgo cmsgo-ubuntu-build/
        cp tmp/cmsgo-admin cmsgo-ubuntu-build/
    - uses: actions/upload-artifact@v3
      with:
        name: cmsgo-ubuntu-build
        path: cmsgo-ubuntu-build